# Simple pod based deployment for K8s based deployment support.
# Also additionally adding resources for better node selector management.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-runner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: job-runner
        image: job-runner:latest
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
      